### PR TITLE
Implemented styling new arrows

### LINKED ISSUE #26: Is it possible to listen creating line between two FlowElements?

### PR DESCRIPTION
**Pull request by SL-Pirate**
This PR adds new styling for the arrows that connects flow elements
This PR is related to #3 

This PR also adds a callback method to handle new connection events between flow elements. Therefore this PR closes #26

### CODE REVIEW

**Comment by alnitak** [comment]
Great PR!

Just a question. I see that ArrowStyle is a dashboard property, wouldn't it be better to have it in the `ArrowParams`?
If I understand well, all the arrows have the style defined in `DashBoard` and it's not possible to have an arrow with a segmented style and another with a curved style simultaneously. 

This is a good update as it is right now and if I understood right and the change would take too much trouble, we can leave the possibility to have a different arrow style on the dashboard for another time.

**Comment by SL-Pirate** [comment]
Actually good point. I shall check and give you an update. 
Although I had this question myself at first I did not think much about it as if someone were to use multiple styling it would make the appearance bad. But again, giving them the availability would be better IG

**Comment by alnitak** [comment]
In the future, we could also consider treating the segment points for a new bezier curve style.

**Comment by SL-Pirate** [comment]
Done.

I moved the arrow style property inside the `ArrowParams` class.
Dashboard will still have the arrow style which is the default style used accross the dashboard but for single arrow it can be overridden.

PS: I will implement a method to update arrow params and give an update

**Comment by SL-Pirate** [comment]
@alnitak I implemented the method
Can you check now?

**Comment by alnitak** [comment]
LGreatTM! :)

I just fixed the position of newly created Pivot(s) points

**Pull request merged**
